// Code generated by protoc-gen-go.
// source: game/core/gamepb/game.proto
// DO NOT EDIT!

/*
Package gamepb is a generated protocol buffer package.

It is generated from these files:
	game/core/gamepb/game.proto

It has these top-level messages:
	Player
	BattleInfoNotify
	Property
	Scene
	SceneNotify
	EnterGameReq
	EnterGameAck
	EnterGameNtf
	LeaveGameNtf
*/
package gamepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Property_Type int32

const (
	Property_GEN   Property_Type = 0
	Property_HEART Property_Type = 1
)

var Property_Type_name = map[int32]string{
	0: "GEN",
	1: "HEART",
}
var Property_Type_value = map[string]int32{
	"GEN":   0,
	"HEART": 1,
}

func (x Property_Type) String() string {
	return proto.EnumName(Property_Type_name, int32(x))
}
func (Property_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type Player struct {
	Id         int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Level      int32  `protobuf:"varint,3,opt,name=level" json:"level,omitempty"`
	Figure     int32  `protobuf:"varint,4,opt,name=figure" json:"figure,omitempty"`
	WeaponType int32  `protobuf:"varint,5,opt,name=weapon_type,json=weaponType" json:"weapon_type,omitempty"`
	Score      int32  `protobuf:"varint,6,opt,name=score" json:"score,omitempty"`
	X          int32  `protobuf:"varint,10,opt,name=x" json:"x,omitempty"`
	Y          int32  `protobuf:"varint,11,opt,name=y" json:"y,omitempty"`
	Life       int32  `protobuf:"varint,12,opt,name=life" json:"life,omitempty"`
	CurLife    int32  `protobuf:"varint,13,opt,name=cur_life,json=curLife" json:"cur_life,omitempty"`
	DefLevel   int32  `protobuf:"varint,14,opt,name=def_level,json=defLevel" json:"def_level,omitempty"`
	SpeedLevel int32  `protobuf:"varint,15,opt,name=speed_level,json=speedLevel" json:"speed_level,omitempty"`
}

func (m *Player) Reset()                    { *m = Player{} }
func (m *Player) String() string            { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()               {}
func (*Player) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Player) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Player) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Player) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *Player) GetFigure() int32 {
	if m != nil {
		return m.Figure
	}
	return 0
}

func (m *Player) GetWeaponType() int32 {
	if m != nil {
		return m.WeaponType
	}
	return 0
}

func (m *Player) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *Player) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Player) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Player) GetLife() int32 {
	if m != nil {
		return m.Life
	}
	return 0
}

func (m *Player) GetCurLife() int32 {
	if m != nil {
		return m.CurLife
	}
	return 0
}

func (m *Player) GetDefLevel() int32 {
	if m != nil {
		return m.DefLevel
	}
	return 0
}

func (m *Player) GetSpeedLevel() int32 {
	if m != nil {
		return m.SpeedLevel
	}
	return 0
}

type BattleInfoNotify struct {
	InfoList []*BattleInfoNotify_PlayerInfo `protobuf:"bytes,1,rep,name=info_list,json=infoList" json:"info_list,omitempty"`
}

func (m *BattleInfoNotify) Reset()                    { *m = BattleInfoNotify{} }
func (m *BattleInfoNotify) String() string            { return proto.CompactTextString(m) }
func (*BattleInfoNotify) ProtoMessage()               {}
func (*BattleInfoNotify) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BattleInfoNotify) GetInfoList() []*BattleInfoNotify_PlayerInfo {
	if m != nil {
		return m.InfoList
	}
	return nil
}

type BattleInfoNotify_PlayerInfo struct {
	Id      int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	CurLife int32 `protobuf:"varint,2,opt,name=cur_life,json=curLife" json:"cur_life,omitempty"`
	X       int32 `protobuf:"varint,3,opt,name=x" json:"x,omitempty"`
	Y       int32 `protobuf:"varint,4,opt,name=y" json:"y,omitempty"`
}

func (m *BattleInfoNotify_PlayerInfo) Reset()                    { *m = BattleInfoNotify_PlayerInfo{} }
func (m *BattleInfoNotify_PlayerInfo) String() string            { return proto.CompactTextString(m) }
func (*BattleInfoNotify_PlayerInfo) ProtoMessage()               {}
func (*BattleInfoNotify_PlayerInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *BattleInfoNotify_PlayerInfo) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BattleInfoNotify_PlayerInfo) GetCurLife() int32 {
	if m != nil {
		return m.CurLife
	}
	return 0
}

func (m *BattleInfoNotify_PlayerInfo) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *BattleInfoNotify_PlayerInfo) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Property struct {
	Type Property_Type `protobuf:"varint,1,opt,name=type,enum=gamepb.Property_Type" json:"type,omitempty"`
	X    int32         `protobuf:"varint,2,opt,name=x" json:"x,omitempty"`
	Y    int32         `protobuf:"varint,3,opt,name=y" json:"y,omitempty"`
}

func (m *Property) Reset()                    { *m = Property{} }
func (m *Property) String() string            { return proto.CompactTextString(m) }
func (*Property) ProtoMessage()               {}
func (*Property) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Property) GetType() Property_Type {
	if m != nil {
		return m.Type
	}
	return Property_GEN
}

func (m *Property) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Property) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Scene struct {
	PropertyList []*Property `protobuf:"bytes,1,rep,name=property_list,json=propertyList" json:"property_list,omitempty"`
}

func (m *Scene) Reset()                    { *m = Scene{} }
func (m *Scene) String() string            { return proto.CompactTextString(m) }
func (*Scene) ProtoMessage()               {}
func (*Scene) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Scene) GetPropertyList() []*Property {
	if m != nil {
		return m.PropertyList
	}
	return nil
}

type SceneNotify struct {
	PropertyIncList []*Property `protobuf:"bytes,1,rep,name=property_inc_list,json=propertyIncList" json:"property_inc_list,omitempty"`
	PropertyDecList []*Property `protobuf:"bytes,2,rep,name=property_dec_list,json=propertyDecList" json:"property_dec_list,omitempty"`
}

func (m *SceneNotify) Reset()                    { *m = SceneNotify{} }
func (m *SceneNotify) String() string            { return proto.CompactTextString(m) }
func (*SceneNotify) ProtoMessage()               {}
func (*SceneNotify) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SceneNotify) GetPropertyIncList() []*Property {
	if m != nil {
		return m.PropertyIncList
	}
	return nil
}

func (m *SceneNotify) GetPropertyDecList() []*Property {
	if m != nil {
		return m.PropertyDecList
	}
	return nil
}

type EnterGameReq struct {
	RoomType int32 `protobuf:"varint,1,opt,name=room_type,json=roomType" json:"room_type,omitempty"`
	Figure   int32 `protobuf:"varint,2,opt,name=figure" json:"figure,omitempty"`
}

func (m *EnterGameReq) Reset()                    { *m = EnterGameReq{} }
func (m *EnterGameReq) String() string            { return proto.CompactTextString(m) }
func (*EnterGameReq) ProtoMessage()               {}
func (*EnterGameReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *EnterGameReq) GetRoomType() int32 {
	if m != nil {
		return m.RoomType
	}
	return 0
}

func (m *EnterGameReq) GetFigure() int32 {
	if m != nil {
		return m.Figure
	}
	return 0
}

type EnterGameAck struct {
	//    Scene scene_info = 1;
	//    Player user = 2;
	//    repeated Player other_player_list = 3;
	UserId int32 `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	GameId int32 `protobuf:"varint,2,opt,name=game_id,json=gameId" json:"game_id,omitempty"`
}

func (m *EnterGameAck) Reset()                    { *m = EnterGameAck{} }
func (m *EnterGameAck) String() string            { return proto.CompactTextString(m) }
func (*EnterGameAck) ProtoMessage()               {}
func (*EnterGameAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *EnterGameAck) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *EnterGameAck) GetGameId() int32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

type EnterGameNtf struct {
	UserId int32 `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *EnterGameNtf) Reset()                    { *m = EnterGameNtf{} }
func (m *EnterGameNtf) String() string            { return proto.CompactTextString(m) }
func (*EnterGameNtf) ProtoMessage()               {}
func (*EnterGameNtf) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *EnterGameNtf) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type LeaveGameNtf struct {
	UserId int32 `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *LeaveGameNtf) Reset()                    { *m = LeaveGameNtf{} }
func (m *LeaveGameNtf) String() string            { return proto.CompactTextString(m) }
func (*LeaveGameNtf) ProtoMessage()               {}
func (*LeaveGameNtf) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *LeaveGameNtf) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func init() {
	proto.RegisterType((*Player)(nil), "gamepb.Player")
	proto.RegisterType((*BattleInfoNotify)(nil), "gamepb.BattleInfoNotify")
	proto.RegisterType((*BattleInfoNotify_PlayerInfo)(nil), "gamepb.BattleInfoNotify.PlayerInfo")
	proto.RegisterType((*Property)(nil), "gamepb.Property")
	proto.RegisterType((*Scene)(nil), "gamepb.Scene")
	proto.RegisterType((*SceneNotify)(nil), "gamepb.SceneNotify")
	proto.RegisterType((*EnterGameReq)(nil), "gamepb.EnterGameReq")
	proto.RegisterType((*EnterGameAck)(nil), "gamepb.EnterGameAck")
	proto.RegisterType((*EnterGameNtf)(nil), "gamepb.EnterGameNtf")
	proto.RegisterType((*LeaveGameNtf)(nil), "gamepb.LeaveGameNtf")
	proto.RegisterEnum("gamepb.Property_Type", Property_Type_name, Property_Type_value)
}

func init() { proto.RegisterFile("game/core/gamepb/game.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 521 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x93, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xb1, 0x13, 0x3b, 0xc9, 0x24, 0x4d, 0xc3, 0x8a, 0x3f, 0x4b, 0x7b, 0x68, 0x64, 0x0e,
	0x84, 0x4b, 0x2a, 0x15, 0x71, 0x43, 0xa8, 0x05, 0xa2, 0x12, 0x29, 0x8a, 0x2a, 0xb7, 0x77, 0xcb,
	0xb5, 0xc7, 0x95, 0x85, 0xe3, 0x35, 0x9b, 0x4d, 0xa9, 0x1f, 0x81, 0x57, 0xe0, 0x0d, 0x78, 0x4b,
	0xb4, 0xb3, 0x76, 0xea, 0x14, 0x41, 0x4f, 0xd9, 0xf9, 0xe6, 0x9b, 0x5f, 0xc6, 0x9f, 0xd7, 0x70,
	0x78, 0x13, 0xae, 0xf0, 0x38, 0x12, 0x12, 0x8f, 0xf5, 0xa9, 0xb8, 0xa6, 0x9f, 0x69, 0x21, 0x85,
	0x12, 0xcc, 0x35, 0x92, 0xf7, 0xcb, 0x06, 0xf7, 0x22, 0x0b, 0x4b, 0x94, 0x6c, 0x08, 0x76, 0x1a,
	0x73, 0x6b, 0x6c, 0x4d, 0x1c, 0xdf, 0x4e, 0x63, 0xc6, 0xa0, 0x9d, 0x87, 0x2b, 0xe4, 0xf6, 0xd8,
	0x9a, 0xf4, 0x7c, 0x3a, 0xb3, 0x67, 0xe0, 0x64, 0x78, 0x8b, 0x19, 0x6f, 0x91, 0xcd, 0x14, 0xec,
	0x05, 0xb8, 0x49, 0x7a, 0xb3, 0x91, 0xc8, 0xdb, 0x24, 0x57, 0x15, 0x3b, 0x82, 0xfe, 0x0f, 0x0c,
	0x0b, 0x91, 0x07, 0xaa, 0x2c, 0x90, 0x3b, 0xd4, 0x04, 0x23, 0x5d, 0x95, 0x05, 0xe1, 0xd6, 0x7a,
	0x41, 0xee, 0x1a, 0x1c, 0x15, 0x6c, 0x00, 0xd6, 0x1d, 0x07, 0x52, 0xac, 0x3b, 0x5d, 0x95, 0xbc,
	0x6f, 0xaa, 0x52, 0x2f, 0x95, 0xa5, 0x09, 0xf2, 0x01, 0x09, 0x74, 0x66, 0xaf, 0xa0, 0x1b, 0x6d,
	0x64, 0x40, 0xfa, 0x1e, 0xe9, 0x9d, 0x68, 0x23, 0x17, 0xba, 0x75, 0x08, 0xbd, 0x18, 0x93, 0xc0,
	0xec, 0x3c, 0xa4, 0x5e, 0x37, 0xc6, 0x64, 0x41, 0x6b, 0x1f, 0x41, 0x7f, 0x5d, 0x20, 0xc6, 0x55,
	0x7b, 0xdf, 0xac, 0x47, 0x12, 0x19, 0xbc, 0xdf, 0x16, 0x8c, 0x3e, 0x85, 0x4a, 0x65, 0x38, 0xcf,
	0x13, 0xb1, 0x14, 0x2a, 0x4d, 0x4a, 0x76, 0x0a, 0xbd, 0x34, 0x4f, 0x44, 0x90, 0xa5, 0x6b, 0xc5,
	0xad, 0x71, 0x6b, 0xd2, 0x3f, 0x79, 0x3d, 0x35, 0x69, 0x4e, 0x1f, 0x9a, 0xa7, 0x26, 0x5a, 0x2d,
	0xf8, 0x5d, 0x3d, 0xb5, 0x48, 0xd7, 0xea, 0xe0, 0x12, 0xe0, 0x5e, 0xff, 0x2b, 0xf6, 0xe6, 0xd3,
	0xd8, 0xbb, 0x4f, 0x43, 0xc1, 0xb4, 0x76, 0x82, 0x69, 0x57, 0xc1, 0x78, 0x2b, 0xe8, 0x5e, 0x48,
	0x51, 0xa0, 0x54, 0x25, 0x7b, 0x0b, 0x6d, 0x0a, 0x5c, 0x43, 0x87, 0x27, 0xcf, 0xeb, 0xed, 0xea,
	0xfe, 0x54, 0x67, 0xef, 0x93, 0xc5, 0x20, 0xed, 0x1d, 0x64, 0xab, 0x46, 0x1e, 0x40, 0x9b, 0xde,
	0x52, 0x07, 0x5a, 0xe7, 0xb3, 0xe5, 0xe8, 0x09, 0xeb, 0x81, 0xf3, 0x75, 0x76, 0xe6, 0x5f, 0x8d,
	0x2c, 0xef, 0x23, 0x38, 0x97, 0x11, 0xe6, 0xc8, 0xde, 0xc3, 0x5e, 0x51, 0x71, 0x9b, 0x91, 0x8c,
	0x1e, 0xfe, 0xa9, 0x3f, 0xa8, 0x6d, 0x3a, 0x03, 0xef, 0xa7, 0x05, 0x7d, 0x02, 0x54, 0xa9, 0x7e,
	0x80, 0xa7, 0x5b, 0x4c, 0x9a, 0x47, 0xff, 0x47, 0xed, 0xd7, 0xd6, 0x79, 0x1e, 0x69, 0xda, 0xce,
	0x74, 0x8c, 0xd5, 0xb4, 0xfd, 0xd8, 0xf4, 0x17, 0xa4, 0x69, 0xef, 0x33, 0x0c, 0x66, 0xb9, 0x42,
	0x79, 0x1e, 0xae, 0xd0, 0xc7, 0xef, 0xfa, 0xd2, 0x48, 0x21, 0x56, 0xc1, 0x36, 0x43, 0xc7, 0xef,
	0x6a, 0x81, 0xc2, 0xb8, 0xbf, 0xeb, 0x76, 0xf3, 0xae, 0x7b, 0xa7, 0x0d, 0xc8, 0x59, 0xf4, 0x8d,
	0xbd, 0x84, 0xce, 0x66, 0x8d, 0x32, 0xd8, 0xbe, 0x5b, 0x57, 0x97, 0xf3, 0x58, 0x37, 0xf4, 0x46,
	0xba, 0x51, 0x11, 0x74, 0x39, 0x8f, 0xbd, 0x37, 0x0d, 0xc2, 0x52, 0x25, 0xff, 0x24, 0x68, 0xe3,
	0x02, 0xc3, 0x5b, 0x7c, 0xcc, 0x78, 0xed, 0xd2, 0xb7, 0xfe, 0xee, 0x4f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xf0, 0x6f, 0x6d, 0x2f, 0x0a, 0x04, 0x00, 0x00,
}
