// Code generated by "stringer -type=Cmd"; DO NOT EDIT

package com

import "fmt"

const (
	_Cmd_name_0 = "Agent_StartAgent_HeartbeatReqAgent_HeartbeatAckAgent_LoginReqAgent_LoginAckAgent_End"
	_Cmd_name_1 = "Game_StartGame_EnterGameReqGame_EnterGameAckGame_EnterGameNtfGame_LeaveGameReqGame_LeaveGameNtfGame_GameMgrEndGame_End"
)

var (
	_Cmd_index_0 = [...]uint8{0, 11, 29, 47, 61, 75, 84}
	_Cmd_index_1 = [...]uint8{0, 10, 27, 44, 61, 78, 95, 110, 118}
)

func (i Cmd) String() string {
	switch {
	case 0 <= i && i <= 5:
		return _Cmd_name_0[_Cmd_index_0[i]:_Cmd_index_0[i+1]]
	case 1006 <= i && i <= 1013:
		i -= 1006
		return _Cmd_name_1[_Cmd_index_1[i]:_Cmd_index_1[i+1]]
	default:
		return fmt.Sprintf("Cmd(%d)", i)
	}
}
