// Code generated by protoc-gen-go.
// source: agent/logic/agentpb/agent.proto
// DO NOT EDIT!

/*
Package agentpb is a generated protocol buffer package.

It is generated from these files:
	agent/logic/agentpb/agent.proto

It has these top-level messages:
	HeartbeatAck
	LoginAck
	LoginReq
*/
package agentpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HeartbeatAck struct {
	SeqId uint32 `protobuf:"varint,1,opt,name=seq_id,json=seqId" json:"seq_id,omitempty"`
}

func (m *HeartbeatAck) Reset()                    { *m = HeartbeatAck{} }
func (m *HeartbeatAck) String() string            { return proto.CompactTextString(m) }
func (*HeartbeatAck) ProtoMessage()               {}
func (*HeartbeatAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HeartbeatAck) GetSeqId() uint32 {
	if m != nil {
		return m.SeqId
	}
	return 0
}

type LoginAck struct {
	UserId int32 `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *LoginAck) Reset()                    { *m = LoginAck{} }
func (m *LoginAck) String() string            { return proto.CompactTextString(m) }
func (*LoginAck) ProtoMessage()               {}
func (*LoginAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginAck) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type LoginReq struct {
	Platform      string `protobuf:"bytes,1,opt,name=platform" json:"platform,omitempty"`
	ClientVersion string `protobuf:"bytes,2,opt,name=client_version,json=clientVersion" json:"client_version,omitempty"`
	DeviceName    string `protobuf:"bytes,3,opt,name=device_name,json=deviceName" json:"device_name,omitempty"`
	DeviceId      string `protobuf:"bytes,4,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
}

func (m *LoginReq) Reset()                    { *m = LoginReq{} }
func (m *LoginReq) String() string            { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()               {}
func (*LoginReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LoginReq) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *LoginReq) GetClientVersion() string {
	if m != nil {
		return m.ClientVersion
	}
	return ""
}

func (m *LoginReq) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *LoginReq) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func init() {
	proto.RegisterType((*HeartbeatAck)(nil), "agentpb.HeartbeatAck")
	proto.RegisterType((*LoginAck)(nil), "agentpb.LoginAck")
	proto.RegisterType((*LoginReq)(nil), "agentpb.LoginReq")
}

func init() { proto.RegisterFile("agent/logic/agentpb/agent.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x3c, 0xcf, 0x41, 0x4b, 0x86, 0x30,
	0x1c, 0xc7, 0x71, 0xac, 0x1e, 0x1f, 0xfd, 0x97, 0x1d, 0x06, 0xd1, 0xa8, 0x83, 0x61, 0x08, 0x9d,
	0xf2, 0xd0, 0x2b, 0xe8, 0x96, 0x10, 0x1d, 0x76, 0xe8, 0x2a, 0x73, 0xfb, 0x27, 0x23, 0xdd, 0x74,
	0x5b, 0xbe, 0x89, 0xde, 0x74, 0xb8, 0xd9, 0x73, 0xda, 0x7e, 0x5f, 0x3e, 0x30, 0x06, 0x25, 0x1f,
	0x50, 0xfb, 0x66, 0x34, 0x83, 0x12, 0x4d, 0xb8, 0xcf, 0x7d, 0x3c, 0x9f, 0x67, 0x6b, 0xbc, 0x21,
	0xc7, 0x3d, 0x56, 0x35, 0x5c, 0xbd, 0x21, 0xb7, 0xbe, 0x47, 0xee, 0x5f, 0xc5, 0x37, 0xb9, 0x81,
	0xd4, 0xe1, 0xd2, 0x29, 0x49, 0x93, 0x87, 0xe4, 0xa9, 0x60, 0x07, 0x87, 0x4b, 0x2b, 0xab, 0x47,
	0xc8, 0xde, 0xcd, 0xa0, 0xf4, 0x46, 0x6e, 0xe1, 0xf8, 0xe3, 0xd0, 0xfe, 0x9b, 0x03, 0x4b, 0xb7,
	0xd9, 0xca, 0xea, 0x37, 0xd9, 0x15, 0xc3, 0x85, 0xdc, 0x41, 0x36, 0x8f, 0xdc, 0x7f, 0x19, 0x3b,
	0x05, 0x96, 0xb3, 0xd3, 0x26, 0x35, 0x5c, 0x8b, 0x51, 0xa1, 0xf6, 0xdd, 0x8a, 0xd6, 0x29, 0xa3,
	0xe9, 0x59, 0x10, 0x45, 0xac, 0x9f, 0x31, 0x92, 0x12, 0x2e, 0x25, 0xae, 0x4a, 0x60, 0xa7, 0xf9,
	0x84, 0xf4, 0x3c, 0x18, 0x88, 0xe9, 0x83, 0x4f, 0x48, 0xee, 0x21, 0xdf, 0x81, 0x92, 0xf4, 0x22,
	0x3e, 0x12, 0x43, 0x2b, 0xfb, 0x34, 0xfc, 0xf4, 0xe5, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xcf, 0x24,
	0x72, 0xdb, 0x0c, 0x01, 0x00, 0x00,
}
